import { HeadersTable } from "@/components/tables/TableComponent";

const headersTableD01P1  = [
  { id: "validasi", label: "Validasi Code" },
  { id: "validasiDeskripsi", label: "Validasi Deskripsi" },
  { id: "nomorCifDebitur", label: "Nomor CIF Debitur" },
  { id: "jenisIdentitas", label: "Jenis Identitas" },
  { id: "nomorIdentitas", label: "Nomor Identitas" },
  { id: "namaSesuaiIdentitas", label: "Nama Sesuai Identitas" },
  { id: "namaLengkap", label: "Nama Lengkap" },
  { id: "kodeStatusPendidikanatauGelarDebitur", label: "Kode Status Pendidikan atau Gelar Debitur" },
  { id: "jenisKelamin", label: "Jenis Kelamin" },
  { id: "tempatLahir", label: "Tempat Lahir" },
  { id: "tanggalLahir", label: "Tanggal Lahir" },
  { id: "nomorPokokWajibPajak", label: "Nomor Pokok Wajib Pajak" },
  { id: "alamat", label: "Alamat" },
  { id: "kelurahan", label: "Kelurahan" },
  { id: "kecamatan", label: "Kecamatan" },
  { id: "kodeKabupatenatauKota", label: "Kode Kabupaten atau Kota" },
  { id: "kodePos", label: "Kode Pos" },
  { id: "nomorTelepon", label: "Nomor Telepon" },
  { id: "nomorTeleponSeluler", label: "Nomor Telepon Seluler" },
  { id: "alamatSuratElektronik", label: "Alamat Surat Elektronik" },
  { id: "kodeNegaraDomisili", label: "Kode Negara Domisili" },
  { id: "kodePekerjaan", label: "Kode Pekerjaan" },
  { id: "tempatBekerja", label: "Tempat Bekerja" },
  { id: "kodeBidangUsahaTempatBekerja", label: "Kode Bidang Usaha Tempat Bekerja" },
  { id: "alamatTempatBekerja", label: "Alamat Tempat Bekerja" },
  { id: "penghasilanKotorPertahun", label: "Penghasilan Kotor Pertahun" },
  { id: "kodeSumberPenghasilan", label: "Kode Sumber Penghasilan" },
  { id: "jumlahTanggungan", label: "Jumlah Tanggungan" },
  { id: "kodeHubunganDenganPelapor", label: "Kode Hubungan Dengan Pelapor" },
  { id: "kodeGolonganDebitur", label: "Kode Golongan Debitur" },
  { id: "statusPerkawinanDebitur", label: "Status Perkawinan Debitur" },
  { id: "nomorIdentitasPasangan", label: "Nomor Identitas Pasangan" },
  { id: "namaPasangan", label: "Nama Pasangan" },
  { id: "tanggalLahirPasangan", label: "Tanggal Lahir Pasangan" },
  { id: "perjanjianPisahHarta", label: "Perjanjian Pisah Harta" },
  { id: "melanggarBMPKBMPDBMPP", label: "Melanggar BMPK BMPD BMPP" },
  { id: "melampauiBMPKBMPDBMPP", label: "Melampaui BMPK BMPD BMPP" },
  { id: "namaGadisIbuKandung", label: "Nama Gadis Ibu Kandung" },
  { id: "kodeKantorCabang", label: "Kode Kantor Cabang" },
  { id: "operasiData", label: "Operasi Data" },
];

export const headersTableD01P1Version2: HeadersTable[]  = [
  { id: "validasi", label: "Validasi Code", options: {disable: true, isEllipsisText: true} },
  { id: "validasiDeskripsi", label: "Validasi Deskripsi", options: {disable: true, isEllipsisText: true} },
  { id: "nomorCifDebitur", label: "Nomor CIF Debitur", options: {disable: true, isPrimaryKey: true} },
  { id: "jenisIdentitas", label: "Jenis Identitas" },
  { id: "nomorIdentitas", label: "Nomor Identitas" },
  { id: "namaSesuaiIdentitas", label: "Nama Sesuai Identitas" },
  { id: "namaLengkap", label: "Nama Lengkap" },
  { id: "kodeStatusPendidikanatauGelarDebitur", label: "Kode Status Pendidikan atau Gelar Debitur" },
  { id: "jenisKelamin", label: "Jenis Kelamin" },
  { id: "tempatLahir", label: "Tempat Lahir" },
  { id: "tanggalLahir", label: "Tanggal Lahir", options: {dateTimeFormat: "YYYY/MM/DD"} },
  { id: "nomorPokokWajibPajak", label: "Nomor Pokok Wajib Pajak" },
  { id: "alamat", label: "Alamat" },
  { id: "kelurahan", label: "Kelurahan" },
  { id: "kecamatan", label: "Kecamatan" },
  { id: "kodeKabupatenatauKota", label: "Kode Kabupaten atau Kota" },
  { id: "kodePos", label: "Kode Pos" },
  { id: "nomorTelepon", label: "Nomor Telepon" },
  { id: "nomorTeleponSeluler", label: "Nomor Telepon Seluler" },
  { id: "alamatSuratElektronik", label: "Alamat Surat Elektronik" },
  { id: "kodeNegaraDomisili", label: "Kode Negara Domisili" },
  { id: "kodePekerjaan", label: "Kode Pekerjaan" },
  { id: "tempatBekerja", label: "Tempat Bekerja" },
  { id: "kodeBidangUsahaTempatBekerja", label: "Kode Bidang Usaha Tempat Bekerja" },
  { id: "alamatTempatBekerja", label: "Alamat Tempat Bekerja" },
  { id: "penghasilanKotorPertahun", label: "Penghasilan Kotor Pertahun", options: {isCurrencyFormat: true} },
  { id: "kodeSumberPenghasilan", label: "Kode Sumber Penghasilan" },
  { id: "jumlahTanggungan", label: "Jumlah Tanggungan" },
  { id: "kodeHubunganDenganPelapor", label: "Kode Hubungan Dengan Pelapor" },
  { id: "kodeGolonganDebitur", label: "Kode Golongan Debitur" },
  { id: "statusPerkawinanDebitur", label: "Status Perkawinan Debitur" },
  { id: "nomorIdentitasPasangan", label: "Nomor Identitas Pasangan" },
  { id: "namaPasangan", label: "Nama Pasangan" },
  { id: "tanggalLahirPasangan", label: "Tanggal Lahir Pasangan", },
  { id: "perjanjianPisahHarta", label: "Perjanjian Pisah Harta" },
  { id: "melanggarBMPKBMPDBMPP", label: "Melanggar BMPK BMPD BMPP" },
  { id: "melampauiBMPKBMPDBMPP", label: "Melampaui BMPK BMPD BMPP" },
  { id: "namaGadisIbuKandung", label: "Nama Gadis Ibu Kandung" },
  { id: "kodeKantorCabang", label: "Kode Kantor Cabang" },
  { id: "operasiData", label: "Operasi Data" },
];

export const headersTableF01P1Version2: HeadersTable[]  = [
  { id: "validasi", label: "Validasi Code", options: {disable: true, isEllipsisText: true} },
  { id: "validasiDeskripsi", label: "Validasi Deskripsi", options: {disable: true, isEllipsisText: true} },
  { id: "nomorCifDebitur", label: "Nomor CIF Debitur", options: {disable: true, isPrimaryKey: true} },
  { id: "nomorRekeningFasilitas", label: "Nomor Rekening Fasilitas", options: {disable: true, isPrimaryKey: true} },
  { id: "kodeSifatKreditatauPembiayaan", label: "Kode Sifat Kredit atau Pembiayaan" },
  { id: "kodeJenisKreditatauPembiayaan", label: "Kode Jenis Kredit atau Pembiayaan" },
  { id: "kodeAkadKreditatauAkadPembiayaan", label: "Kode Akad Kredit atau Akad Pembiayaan" },
  { id: "nomorAkadAwal", label: "Nomor Akad Awal" },
  { id: "tanggalAkadAwal", label: "Tanggal Akad Awal" },
  { id: "nomorAkadAkhir", label: "Nomor Akad Akhir" },
  { id: "tanggalAkadAkhir", label: "Tanggal Akad Akhir" },
  { id: "frekuensiPerpanjanganFasilitasKreditatauPembiayaan", label: "Frekuensi Perpanjangan Fasilitas Kredit atau Pembiayaan" },
  { id: "tanggalAwalKreditatauPembiayaan", label: "Tanggal Awal Kredit atau Pembiayaan" },
  { id: "tanggalMulai", label: "Tanggal Mulai" },
  { id: "tanggalJatuhTempo", label: "Tanggal Jatuh Tempo" },
  { id: "kodeKategoriDebitur", label: "Kode Kategori Debitur" },
  { id: "kodeJenisPenggunaan", label: "Kode Jenis Penggunaan" },
  { id: "kodeOrientasiPenggunaan", label: "Kode Orientasi Penggunaan" },
  { id: "kodeSektorEkonomi", label: "Kode Sektor Ekonomi" },
  { id: "kodeKabupatenatauKotaLokasiProyek", label: "Kode Kabupaten atau Kota Lokasi Proyek" },
  { id: "nilaiProyek", label: "Nilai Proyek" },
  { id: "kodeValuta", label: "Kode Valuta" },
  { id: "sukuBungaatauImbalan", label: "Suku Bunga atau Imbalan" },
  { id: "jenisSukuBungaatauImbalan", label: "Jenis Suku Bunga atau Imbalan" },
  { id: "kreditatauPembiayaanProgramPemerintah", label: "Kredit atau Pembiayaan Program Pemerintah" },
  { id: "asalKreditatauPembiayaanTakeover", label: "Asal Kredit atau Pembiayaan Takeover" },
  { id: "sumberDana", label: "Sumber Dana" },
  { id: "plafonAwal", label: "Plafon Awal" },
  { id: "plafon", label: "Plafon" },
  { id: "realisasiatauPencairanBulanBerjalan", label: "Realisasi atau Pencairan Bulan Berjalan" },
  { id: "denda", label: "Denda" },
  { id: "bakiDebet", label: "Baki Debet" },
  { id: "nilaiDalamMataUangAsal", label: "Nilai Dalam Mata Uang Asal" },
  { id: "kodeKualitasKreditatauPembiayaan", label: "Kode Kualitas Kredit atau Pembiayaan" },
  { id: "tanggalMacet", label: "Tanggal Macet" },
  { id: "kodeSebabMacet", label: "Kode Sebab Macet" },
  { id: "tunggakanPokok", label: "Tunggakan Pokok" },
  { id: "tunggakanBungaatauImbalan", label: "Tunggakan Bunga atau Imbalan" },
  { id: "jumlahHariTunggakan", label: "Jumlah Hari Tunggakan" },
  { id: "frekuensiTunggakan", label: "Frekuensi Tunggakan" },
  { id: "frekuensiRestrukturirasi", label: "Frekuensi Restrukturirasi" },
  { id: "tanggalRestrukturisasiAwal", label: "Tanggal Restrukturisasi Awal" },
  { id: "tanggalRestrukturisasiAkhir", label: "Tanggal Restrukturisasi Akhir" },
  { id: "kodeCaraRestrukturisasi", label: "Kode Cara Restrukturisasi" },
  { id: "kodeKondisi", label: "Kode Kondisi" },
  { id: "tanggalKondisi", label: "Tanggal Kondisi" },
  { id: "keterangan", label: "Keterangan" },
  { id: "kodeKantorCabang", label: "Kode Kantor Cabang" },
  { id: "operasiData", label: "Operasi Data" },
];

const headersTableF01P1  = [
  { id: "validasi", label: "Validasi Code" },
  { id: "validasiDeskripsi", label: "Validasi Deskripsi" },
  { id: "nomorCifDebitur", label: "Nomor CIF Debitur" },
  { id: "nomorRekeningFasilitas", label: "Nomor Rekening Fasilitas" },
  { id: "kodeSifatKreditatauPembiayaan", label: "Kode Sifat Kredit atau Pembiayaan" },
  { id: "kodeJenisKreditatauPembiayaan", label: "Kode Jenis Kredit atau Pembiayaan" },
  { id: "kodeAkadKreditatauAkadPembiayaan", label: "Kode Akad Kredit atau Akad Pembiayaan" },
  { id: "nomorAkadAwal", label: "Nomor Akad Awal" },
  { id: "tanggalAkadAwal", label: "Tanggal Akad Awal" },
  { id: "nomorAkadAkhir", label: "Nomor Akad Akhir" },
  { id: "tanggalAkadAkhir", label: "Tanggal Akad Akhir" },
  { id: "frekuensiPerpanjanganFasilitasKreditatauPembiayaan", label: "Frekuensi Perpanjangan Fasilitas Kredit atau Pembiayaan" },
  { id: "tanggalAwalKreditatauPembiayaan", label: "Tanggal Awal Kredit atau Pembiayaan" },
  { id: "tanggalMulai", label: "Tanggal Mulai" },
  { id: "tanggalJatuhTempo", label: "Tanggal Jatuh Tempo" },
  { id: "kodeKategoriDebitur", label: "Kode Kategori Debitur" },
  { id: "kodeJenisPenggunaan", label: "Kode Jenis Penggunaan" },
  { id: "kodeOrientasiPenggunaan", label: "Kode Orientasi Penggunaan" },
  { id: "kodeSektorEkonomi", label: "Kode Sektor Ekonomi" },
  { id: "kodeKabupatenatauKotaLokasiProyek", label: "Kode Kabupaten atau Kota Lokasi Proyek" },
  { id: "nilaiProyek", label: "Nilai Proyek" },
  { id: "kodeValuta", label: "Kode Valuta" },
  { id: "sukuBungaatauImbalan", label: "Suku Bunga atau Imbalan" },
  { id: "jenisSukuBungaatauImbalan", label: "Jenis Suku Bunga atau Imbalan" },
  { id: "kreditatauPembiayaanProgramPemerintah", label: "Kredit atau Pembiayaan Program Pemerintah" },
  { id: "asalKreditatauPembiayaanTakeover", label: "Asal Kredit atau Pembiayaan Takeover" },
  { id: "sumberDana", label: "Sumber Dana" },
  { id: "plafonAwal", label: "Plafon Awal" },
  { id: "plafon", label: "Plafon" },
  { id: "realisasiatauPencairanBulanBerjalan", label: "Realisasi atau Pencairan Bulan Berjalan" },
  { id: "denda", label: "Denda" },
  { id: "bakiDebet", label: "Baki Debet" },
  { id: "nilaiDalamMataUangAsal", label: "Nilai Dalam Mata Uang Asal" },
  { id: "kodeKualitasKreditatauPembiayaan", label: "Kode Kualitas Kredit atau Pembiayaan" },
  { id: "tanggalMacet", label: "Tanggal Macet" },
  { id: "kodeSebabMacet", label: "Kode Sebab Macet" },
  { id: "tunggakanPokok", label: "Tunggakan Pokok" },
  { id: "tunggakanBungaatauImbalan", label: "Tunggakan Bunga atau Imbalan" },
  { id: "jumlahHariTunggakan", label: "Jumlah Hari Tunggakan" },
  { id: "frekuensiTunggakan", label: "Frekuensi Tunggakan" },
  { id: "frekuensiRestrukturirasi", label: "Frekuensi Restrukturirasi" },
  { id: "tanggalRestrukturisasiAwal", label: "Tanggal Restrukturisasi Awal" },
  { id: "tanggalRestrukturisasiAkhir", label: "Tanggal Restrukturisasi Akhir" },
  { id: "kodeCaraRestrukturisasi", label: "Kode Cara Restrukturisasi" },
  { id: "kodeKondisi", label: "Kode Kondisi" },
  { id: "tanggalKondisi", label: "Tanggal Kondisi" },
  { id: "keterangan", label: "Keterangan" },
  { id: "kodeKantorCabang", label: "Kode Kantor Cabang" },
  { id: "operasiData", label: "Operasi Data" },
];

export {headersTableD01P1, headersTableF01P1};
