import { HeadersTable } from "@/components/tables/TableComponent";

export const uploadResponseTableHeaderD01: HeadersTable[] = [
  { id: "Error_Code", label: "Error Code", options: {isEllipsisText: true, disable: true} },
  { id: "Error_Message", label: "Error Message", options: {isEllipsisText: true, disable: true} },
  { id: "Nomor_CIF_Debitur", label: "CIF Debitur", options: {isPrimaryKey: true, disable: true} },
  { id: "Jenis_Identitas", label: "Jenis Identitas" },
  { id: "Nomor_Identitas", label: "Nomor Identitas" },
  { id: "Nama_Sesuai_Identitas", label: "Nama Sesuai Identitas" },
  { id: "Nama_Lengkap", label: "Nama Lengkap" },
  { id: "Kode_Status_Pendidikan_atau_Gelar_Debitur", label: "Status Pendidikan/Gelar" },
  { id: "Jenis_Kelamin", label: "Jenis Kelamin" },
  { id: "Tempat_Lahir", label: "Tempat Lahir" },
  { id: "Tanggal_Lahir", label: "Tanggal Lahir" },
  { id: "Nomor_Pokok_Wajib_Pajak", label: "NPWP" },
  { id: "Alamat", label: "Alamat" },
  { id: "Kelurahan", label: "Kelurahan" },
  { id: "Kecamatan", label: "Kecamatan" },
  { id: "Kode_Kabupaten_atau_Kota", label: "Kode Kab/Kota" },
  { id: "Kode_Pos", label: "Kode Pos" },
  { id: "Nomor_Telepon", label: "No. Telepon" },
  { id: "Nomor_Telepon_Seluler", label: "No. HP" },
  { id: "Alamat_Surat_Elektronik", label: "Email" },
  { id: "Kode_Negara_Domisili", label: "Kode Negara Domisili" },
  { id: "Kode_Pekerjaan", label: "Kode Pekerjaan" },
  { id: "Tempat_Bekerja", label: "Tempat Bekerja" },
  { id: "Kode_Bidang_Usaha_Tempat_Bekerja", label: "Bidang Usaha Tempat Bekerja" },
  { id: "Alamat_Tempat_Bekerja", label: "Alamat Tempat Bekerja" },
  { id: "Penghasilan_Kotor_Pertahun", label: "Penghasilan Kotor/Tahun" },
  { id: "Kode_Sumber_Penghasilan", label: "Sumber Penghasilan" },
  { id: "Jumlah_Tanggungan", label: "Jumlah Tanggungan" },
  { id: "Kode_Hubungan_Dengan_Pelapor", label: "Hubungan dgn Pelapor" },
  { id: "Kode_Golongan_Debitur", label: "Golongan Debitur" },
  { id: "Status_Perkawinan_Debitur", label: "Status Perkawinan" },
  { id: "Nomor_Identitas_Pasangan", label: "No Identitas Pasangan" },
  { id: "Nama_Pasangan", label: "Nama Pasangan" },
  { id: "Tanggal_Lahir_Pasangan", label: "Tgl Lahir Pasangan" },
  { id: "Perjanjian_Pisah_Harta", label: "Pisah Harta?" },
  { id: "Melanggar_BMPK_BMPD_BMPP", label: "Melanggar BMPK/BMPD/BMPP?" },
  { id: "Melampaui_BMPK_BMPD_BMPP", label: "Melampaui BMPK/BMPD/BMPP?" },
  { id: "Nama_Gadis_Ibu_Kandung", label: "Nama Ibu Kandung" },
  { id: "Kode_Kantor_Cabang", label: "Kode Cabang" },
  { id: "Operasi_Data", label: "Operasi Data" }
] ;

export const uploadResponseTableHeaderF01: HeadersTable[] = [
  { id: "Error_Code", label: "Error Code", options: {isEllipsisText: true, disable: true} },
  { id: "Error_Message", label: "Error Message", options: {isEllipsisText: true, disable: true} },
  { id: "Nomor_Rekening_Fasilitas", label: "No. Rekening Fasilitas", options: {isPrimaryKey: true, disable: true}},
  { id: "Nomor_CIF_Debitur", label: "CIF Debitur", options: {isPrimaryKey: true, disable: true} },
  { id: "Kode_Sifat_Kredit_atau_Pembiayaan", label: "Sifat Kredit/Pembiayaan" },
  { id: "Kode_Jenis_Kredit_atau_Pembiayaan", label: "Jenis Kredit/Pembiayaan" },
  { id: "Kode_Akad_Kredit_atau_Akad_Pembiayaan", label: "Kode Akad" },
  { id: "Nomor_Akad_Awal", label: "No. Akad Awal" },
  { id: "Tanggal_Akad_Awal", label: "Tgl Akad Awal" },
  { id: "Nomor_Akad_Akhir", label: "No. Akad Akhir" },
  { id: "Tanggal_Akad_Akhir", label: "Tgl Akad Akhir" },
  { id: "Frekuensi_Perpanjangan_Fasilitas_Kredit_atau_Pembiayaan", label: "Frekuensi Perpanjangan" },
  { id: "Tanggal_Awal_Kredit_atau_Pembiayaan", label: "Tgl Awal Kredit" },
  { id: "Tanggal_Mulai", label: "Tgl Mulai" },
  { id: "Tanggal_Jatuh_Tempo", label: "Tgl Jatuh Tempo" },
  { id: "Kode_Kategori_Debitur", label: "Kategori Debitur" },
  { id: "Kode_Jenis_Penggunaan", label: "Jenis Penggunaan" },
  { id: "Kode_Orientasi_Penggunaan", label: "Orientasi Penggunaan" },
  { id: "Kode_Sektor_Ekonomi", label: "Sektor Ekonomi" },
  { id: "Kode_Kabupaten_atau_Kota_Lokasi_Proyek", label: "Lokasi Proyek (Kab/Kota)" },
  { id: "Nilai_Proyek", label: "Nilai Proyek" },
  { id: "Kode_Valuta", label: "Valuta" },
  { id: "Suku_Bunga_atau_Imbalan", label: "Suku Bunga/Imbalan" },
  { id: "Jenis_Suku_Bunga_atau_Imbalan", label: "Jenis Suku Bunga" },
  { id: "Kredit_atau_Pembiayaan_Program_Pemerintah", label: "Program Pemerintah?" },
  { id: "Asal_Kredit_atau_Pembiayaan_Takeover", label: "Asal Kredit Takeover" },
  { id: "Sumber_Dana", label: "Sumber Dana" },
  { id: "Plafon_Awal", label: "Plafon Awal" },
  { id: "Plafon", label: "Plafon" },
  { id: "Realisasi_atau_Pencairan_Bulan_Berjalan", label: "Realisasi Bulan Ini" },
  { id: "Denda", label: "Denda" },
  { id: "Baki_Debet", label: "Baki Debet" },
  { id: "Nilai_Dalam_Mata_Uang_Asal", label: "Nilai Dalam Mata Uang Asal" },
  { id: "Kode_Kualitas_Kredit_atau_Pembiayaan", label: "Kualitas Kredit" },
  { id: "Tanggal_Macet", label: "Tgl Macet" },
  { id: "Kode_Sebab_Macet", label: "Sebab Macet" },
  { id: "Tunggakan_Pokok", label: "Tunggakan Pokok" },
  { id: "Tunggakan_Bunga_atau_Imbalan", label: "Tunggakan Bunga/Imbalan" },
  { id: "Jumlah_Hari_Tunggakan", label: "Hari Tunggakan" },
  { id: "Frekuensi_Tunggakan", label: "Frekuensi Tunggakan" },
  { id: "Frekuensi_Restrukturirasi", label: "Frekuensi Restrukturisasi" },
  { id: "Tanggal_Restrukturisasi_Awal", label: "Tgl Restrukturisasi Awal" },
  { id: "Tanggal_Restrukturisasi_Akhir", label: "Tgl Restrukturisasi Akhir" },
  { id: "Kode_Cara_Restrukturisasi", label: "Cara Restrukturisasi" },
  { id: "Kode_Kondisi", label: "Kode Kondisi" },
  { id: "Tanggal_Kondisi", label: "Tgl Kondisi" },
  { id: "Keterangan", label: "Keterangan" },
  { id: "Kode_Kantor_Cabang", label: "Kode Cabang" },
  { id: "Operasi_Data", label: "Operasi Data" }
];

