export const findErrorMapValidation = (errorCodes: string[]) => {
  const errorCodesLower = errorCodes.map(code => code.toLowerCase());
  return mapErrorCodesValidation.filter(item => errorCodesLower.includes(item.error_code.toLowerCase()));
};

export const mapErrorCodesValidation = [
  {
    "cid" : 1,
    "segment_name" : "D01",
    "v_column" : "nomorCifDebitur",
    "error_code" : "ED001",
    "validation" : "cannot duplicate",
  },
  {
    "cid" : 2,
    "segment_name" : "D01",
    "v_column" : "nomorCifDebitur",
    "error_code" : "ED002",
    "validation" : "cannot use character",
  },
  {
    "cid" : 3,
    "segment_name" : "D01",
    "v_column" : "nomorCifDebitur",
    "error_code" : "ED003",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 4,
    "segment_name" : "D01",
    "v_column" : "jenisIdentitas",
    "error_code" : "ED004",
    "validation" : "length must be 1 characters",
  },
  {
    "cid" : 5,
    "segment_name" : "D01",
    "v_column" : "jenisIdentitas",
    "error_code" : "ED005",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 6,
    "segment_name" : "D01",
    "v_column" : "nomorIdentitas",
    "error_code" : "ED006",
    "validation" : "cannot use character",
  },
  {
    "cid" : 7,
    "segment_name" : "D01",
    "v_column" : "nomorIdentitas",
    "error_code" : "ED007",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 8,
    "segment_name" : "D01",
    "v_column" : "namaSesuaiIdentitas",
    "error_code" : "ED008",
    "validation" : "cannot use title",
  },
  {
    "cid" : 9,
    "segment_name" : "D01",
    "v_column" : "namaSesuaiIdentitas",
    "error_code" : "ED009",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 10,
    "segment_name" : "D01",
    "v_column" : "namaLengkap",
    "error_code" : "ED010",
    "validation" : "please use full name",
  },
  {
    "cid" : 11,
    "segment_name" : "D01",
    "v_column" : "namaLengkap",
    "error_code" : "ED011",
    "validation" : "cannot use title",
  },
  {
    "cid" : 12,
    "segment_name" : "D01",
    "v_column" : "kodeStatusPendidikanatauGelarDebitur",
    "error_code" : "ED012",
    "validation" : "length must be 2 characters",
  },
  {
    "cid" : 13,
    "segment_name" : "D01",
    "v_column" : "kodeStatusPendidikanatauGelarDebitur",
    "error_code" : "ED013",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 14,
    "segment_name" : "D01",
    "v_column" : "jenisKelamin",
    "error_code" : "ED014",
    "validation" : "length must be 1 characters",
  },
  {
    "cid" : 15,
    "segment_name" : "D01",
    "v_column" : "jenisKelamin",
    "error_code" : "ED015",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 16,
    "segment_name" : "D01",
    "v_column" : "tempatLahir",
    "error_code" : "ED016",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 17,
    "segment_name" : "D01",
    "v_column" : "tanggalLahir",
    "error_code" : "ED017",
    "validation" : "length must be 8 characters",
    "description" : "yyyymmdd = 19880425",
  },
  {
    "cid" : 18,
    "segment_name" : "D01",
    "v_column" : "tanggalLahir",
    "error_code" : "ED018",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 19,
    "segment_name" : "D01",
    "v_column" : "nomorPokokWajibPajak",
    "error_code" : "ED019",
    "validation" : "cannot use character",
  },
  {
    "cid" : 20,
    "segment_name" : "D01",
    "v_column" : "alamat",
    "error_code" : "ED020",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 21,
    "segment_name" : "D01",
    "v_column" : "kelurahan",
    "error_code" : "ED021",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 22,
    "segment_name" : "D01",
    "v_column" : "kecamatan",
    "error_code" : "ED022",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 23,
    "segment_name" : "D01",
    "v_column" : "kodeKabupatenatauKota",
    "error_code" : "ED023",
    "validation" : "length must be 4 characters",
  },
  {
    "cid" : 24,
    "segment_name" : "D01",
    "v_column" : "kodeKabupatenatauKota",
    "error_code" : "ED024",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 25,
    "segment_name" : "D01",
    "v_column" : "kodePos",
    "error_code" : "ED025",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 26,
    "segment_name" : "D01",
    "v_column" : "nomorTelepon",
    "error_code" : "ED026",
    "validation" : "cannot use character",
  },
  {
    "cid" : 27,
    "segment_name" : "D01",
    "v_column" : "nomorTelepon",
    "error_code" : "ED027",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 28,
    "segment_name" : "D01",
    "v_column" : "nomorTeleponSeluler",
    "error_code" : "ED028",
    "validation" : "cannot use character",
  },
  {
    "cid" : 29,
    "segment_name" : "D01",
    "v_column" : "kodeNegaraDomisili",
    "error_code" : "ED029",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 30,
    "segment_name" : "D01",
    "v_column" : "kodePekerjaan",
    "error_code" : "ED030",
    "validation" : "length must be 3 characters",
  },
  {
    "cid" : 31,
    "segment_name" : "D01",
    "v_column" : "kodePekerjaan",
    "error_code" : "ED031",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 32,
    "segment_name" : "D01",
    "v_column" : "tempatBekerja",
    "error_code" : "ED032",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 33,
    "segment_name" : "D01",
    "v_column" : "kodeBidangUsahaTempatBekerja",
    "error_code" : "ED033",
    "validation" : "length must be 6 characters",
  },
  {
    "cid" : 34,
    "segment_name" : "D01",
    "v_column" : "kodeBidangUsahaTempatBekerja",
    "error_code" : "ED034",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 35,
    "segment_name" : "D01",
    "v_column" : "penghasilanKotorPertahun",
    "error_code" : "ED035",
    "validation" : "column is mandatory",
    "description" : "sejak diatas 1 juni 2016",
  },
  {
    "cid" : 36,
    "segment_name" : "D01",
    "v_column" : "kodeSumberPenghasilan",
    "error_code" : "ED036",
    "validation" : "length must be 1 characters",
  },
  {
    "cid" : 37,
    "segment_name" : "D01",
    "v_column" : "kodeSumberPenghasilan",
    "error_code" : "ED037",
    "validation" : "column is mandatory",
    "description" : "sejak diatas 1 juni 2016",
  },
  {
    "cid" : 38,
    "segment_name" : "D01",
    "v_column" : "jumlahTanggungan",
    "error_code" : "ED038",
    "validation" : "column is mandatory",
    "description" : "sejak diatas 1 juni 2016",
  },
  {
    "cid" : 39,
    "segment_name" : "D01",
    "v_column" : "kodeHubunganDenganPelapor",
    "error_code" : "ED039",
    "validation" : "length must be 2 characters",
  },
  {
    "cid" : 40,
    "segment_name" : "D01",
    "v_column" : "kodeHubunganDenganPelapor",
    "error_code" : "ED040",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 41,
    "segment_name" : "D01",
    "v_column" : "kodeGolonganDebitur",
    "error_code" : "ED041",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 42,
    "segment_name" : "D01",
    "v_column" : "statusPerkawinanDebitur",
    "error_code" : "ED042",
    "validation" : "length must be 1 characters",
  },
  {
    "cid" : 43,
    "segment_name" : "D01",
    "v_column" : "nomorIdentitasPasangan",
    "error_code" : "ED043",
    "validation" : "column is mandatory",
    "description" : "sejak diatas 1 juni 2016, dikosongkan",
  },
  {
    "cid" : 44,
    "segment_name" : "D01",
    "v_column" : "nomorIdentitasPasangan",
    "error_code" : "ED044",
    "validation" : "cannot use character",
    "description" : "dikosongkan",
  },
  {
    "cid" : 45,
    "segment_name" : "D01",
    "v_column" : "namaPasangan",
    "error_code" : "ED045",
    "validation" : "column is mandatory",
    "description" : "sejak diatas 1 juni 2016, dikosongkan",
  },
  {
    "cid" : 46,
    "segment_name" : "D01",
    "v_column" : "tanggalLahirPasangan",
    "error_code" : "ED046",
    "validation" : "length must be 8 characters",
    "description" : "yyyymmdd = 19880425, dikosongkan",
  },
  {
    "cid" : 47,
    "segment_name" : "D01",
    "v_column" : "tanggalLahirPasangan",
    "error_code" : "ED047",
    "validation" : "column is mandatory",
    "description" : "sejak diatas 1 juni 2016, dikosongkan",
  },
  {
    "cid" : 48,
    "segment_name" : "D01",
    "v_column" : "perjanjianPisahHarta",
    "error_code" : "ED048",
    "validation" : "length must be 1 characters",
    "description" : "dikosongkan",
  },
  {
    "cid" : 49,
    "segment_name" : "D01",
    "v_column" : "perjanjianPisahHarta",
    "error_code" : "ED049",
    "validation" : "column is mandatory",
    "description" : "sejak diatas 1 juni 2016, dikosongkan",
  },
  {
    "cid" : 50,
    "segment_name" : "D01",
    "v_column" : "melanggarBMPKBMPDBMPP",
    "error_code" : "ED050",
    "validation" : "length must be 1 characters",
  },
  {
    "cid" : 51,
    "segment_name" : "D01",
    "v_column" : "melanggarBMPKBMPDBMPP",
    "error_code" : "ED051",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 52,
    "segment_name" : "D01",
    "v_column" : "melampauiBMPKBMPDBMPP",
    "error_code" : "ED052",
    "validation" : "length must be 1 characters",
  },
  {
    "cid" : 53,
    "segment_name" : "D01",
    "v_column" : "melampauiBMPKBMPDBMPP",
    "error_code" : "ED053",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 54,
    "segment_name" : "D01",
    "v_column" : "namaGadisIbuKandung",
    "error_code" : "ED054",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 55,
    "segment_name" : "D01",
    "v_column" : "kodeKantorCabang",
    "error_code" : "ED055",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 56,
    "segment_name" : "D01",
    "v_column" : "nomorIdentitas",
    "error_code" : "ED056",
    "validation" : "length must be 16 characters",
  },
  {
    "cid" : 57,
    "segment_name" : "D01",
    "v_column" : "nomorTeleponSeluler",
    "error_code" : "ED057",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 58,
    "segment_name" : "D02",
    "v_column" : "nomorCifDebitur",
    "error_code" : "ED0201",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 59,
    "segment_name" : "D02",
    "v_column" : "nomorIdentitas_Badan_Usaha",
    "error_code" : "ED0202",
    "validation" : "cannot use character",
  },
  {
    "cid" : 60,
    "segment_name" : "D02",
    "v_column" : "nomorIdentitas_Badan_Usaha",
    "error_code" : "ED0203",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 61,
    "segment_name" : "D02",
    "v_column" : "Nama_Badan_Usaha",
    "error_code" : "ED0204",
    "validation" : "cannot use title",
    "description" : "PT, CV, Koperasi",
  },
  {
    "cid" : 62,
    "segment_name" : "D02",
    "v_column" : "Nama_Badan_Usaha",
    "error_code" : "ED0205",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 63,
    "segment_name" : "D02",
    "v_column" : "Kode_Bentuk_Badan_Usaha",
    "error_code" : "ED0206",
    "validation" : "length must be 2 characters",
  },
  {
    "cid" : 64,
    "segment_name" : "D02",
    "v_column" : "Kode_Bentuk_Badan_Usaha",
    "error_code" : "ED0207",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 65,
    "segment_name" : "D02",
    "v_column" : "Tempat_Pendirian",
    "error_code" : "ED0208",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 66,
    "segment_name" : "D02",
    "v_column" : "Nomor_Akta_Pendirian",
    "error_code" : "ED0209",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 67,
    "segment_name" : "D02",
    "v_column" : "Tanggal_Akta_Pendirian",
    "error_code" : "ED0210",
    "validation" : "length must be 8 characters",
    "description" : "yyyymmdd = 19880425",
  },
  {
    "cid" : 68,
    "segment_name" : "D02",
    "v_column" : "Tanggal_Akta_Pendirian",
    "error_code" : "ED0211",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 69,
    "segment_name" : "D02",
    "v_column" : "Nomor_Akta_Perubahan_Terakhir",
    "error_code" : "ED0212",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 70,
    "segment_name" : "D02",
    "v_column" : "Tanggal_Akta_Perubahan_Terakhir",
    "error_code" : "ED0213",
    "validation" : "length must be 8 characters",
    "description" : "yyyymmdd = 19880425",
  },
  {
    "cid" : 71,
    "segment_name" : "D02",
    "v_column" : "Tanggal_Akta_Perubahan_Terakhir",
    "error_code" : "ED0214",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 72,
    "segment_name" : "D02",
    "v_column" : "nomorTelepon",
    "error_code" : "ED0215",
    "validation" : "cannot use character",
  },
  {
    "cid" : 73,
    "segment_name" : "D02",
    "v_column" : "nomorTelepon",
    "error_code" : "ED0216",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 74,
    "segment_name" : "D02",
    "v_column" : "nomorTeleponSeluler",
    "error_code" : "ED0217",
    "validation" : "cannot use character",
  },
  {
    "cid" : 75,
    "segment_name" : "D02",
    "v_column" : "alamat",
    "error_code" : "ED0218",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 76,
    "segment_name" : "D02",
    "v_column" : "Kelurahan",
    "error_code" : "ED0219",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 77,
    "segment_name" : "D02",
    "v_column" : "Kecamatan",
    "error_code" : "ED0220",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 78,
    "segment_name" : "D02",
    "v_column" : "kodeKabupatenatauKota",
    "error_code" : "ED0221",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 79,
    "segment_name" : "D02",
    "v_column" : "kodeKabupatenatauKota",
    "error_code" : "ED0222",
    "validation" : "Kode Kabupaten atau Kota is not active",
  },
  {
    "cid" : 81,
    "segment_name" : "D02",
    "v_column" : "kodePos",
    "error_code" : "ED0223",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 82,
    "segment_name" : "D02",
    "v_column" : "kodeNegaraDomisili",
    "error_code" : "ED0224",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 83,
    "segment_name" : "D02",
    "v_column" : "Kode_Bidang_Usaha",
    "error_code" : "ED0225",
    "validation" : "length must be 6 characters",
  },
  {
    "cid" : 84,
    "segment_name" : "D02",
    "v_column" : "Kode_Bidang_Usaha",
    "error_code" : "ED0226",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 85,
    "segment_name" : "D02",
    "v_column" : "kodeHubunganDenganPelapor",
    "error_code" : "ED0227",
    "validation" : "length must be 2 characters",
  },
  {
    "cid" : 86,
    "segment_name" : "D02",
    "v_column" : "kodeHubunganDenganPelapor",
    "error_code" : "ED0228",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 87,
    "segment_name" : "D02",
    "v_column" : "melanggarBMPKBMPDBMPP",
    "error_code" : "ED0229",
    "validation" : "length must be 1 characters",
  },
  {
    "cid" : 88,
    "segment_name" : "D02",
    "v_column" : "melanggarBMPKBMPDBMPP",
    "error_code" : "ED0230",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 89,
    "segment_name" : "D02",
    "v_column" : "melampauiBMPKBMPDBMPP",
    "error_code" : "ED0231",
    "validation" : "length must be 1 characters",
  },
  {
    "cid" : 90,
    "segment_name" : "D02",
    "v_column" : "melampauiBMPKBMPDBMPP",
    "error_code" : "ED0232",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 91,
    "segment_name" : "D02",
    "v_column" : "Go_Public",
    "error_code" : "ED0233",
    "validation" : "length must be 1 characters",
  },
  {
    "cid" : 92,
    "segment_name" : "D02",
    "v_column" : "Go_Public",
    "error_code" : "ED0234",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 93,
    "segment_name" : "D02",
    "v_column" : "kodeGolonganDebitur",
    "error_code" : "ED0235",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 94,
    "segment_name" : "D02",
    "v_column" : "Lembaga_Pemeringkat",
    "error_code" : "ED0236",
    "validation" : "length must be 3 characters",
  },
  {
    "cid" : 95,
    "segment_name" : "D02",
    "v_column" : "Lembaga_Pemeringkat",
    "error_code" : "ED0237",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 96,
    "segment_name" : "D02",
    "v_column" : "Tanggal_Pemeringkatan",
    "error_code" : "ED0238",
    "validation" : "length must be 8 characters",
    "description" : "yyyymmdd = 19880425",
  },
  {
    "cid" : 97,
    "segment_name" : "D02",
    "v_column" : "Tanggal_Pemeringkatan",
    "error_code" : "ED0239",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 98,
    "segment_name" : "D02",
    "v_column" : "kodeKantorCabang",
    "error_code" : "ED0240",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 99,
    "segment_name" : "F01",
    "v_column" : "nomorRekeningFasilitas",
    "error_code" : "EF001",
    "validation" : "cannot duplicate",
  },
  {
    "cid" : 100,
    "segment_name" : "F01",
    "v_column" : "nomorRekeningFasilitas",
    "error_code" : "EF002",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 101,
    "segment_name" : "F01",
    "v_column" : "nomorRekeningFasilitas",
    "error_code" : "EF003",
    "validation" : "cannot use character",
  },
  {
    "cid" : 102,
    "segment_name" : "F01",
    "v_column" : "nomorCifDebitur",
    "error_code" : "EF004",
    "validation" : "cannot use character",
  },
  {
    "cid" : 103,
    "segment_name" : "F01",
    "v_column" : "nomorCifDebitur",
    "error_code" : "EF005",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 104,
    "segment_name" : "F01",
    "v_column" : "kodeSifatKreditatauPembiayaan",
    "error_code" : "EF006",
    "validation" : "length must be 1 characters",
  },
  {
    "cid" : 105,
    "segment_name" : "F01",
    "v_column" : "kodeSifatKreditatauPembiayaan",
    "error_code" : "EF007",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 106,
    "segment_name" : "F01",
    "v_column" : "kodeJenisKreditatauPembiayaan",
    "error_code" : "EF008",
    "validation" : "length must be 3 characters",
  },
  {
    "cid" : 107,
    "segment_name" : "F01",
    "v_column" : "kodeJenisKreditatauPembiayaan",
    "error_code" : "EF009",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 108,
    "segment_name" : "F01",
    "v_column" : "kodeAkadKreditatauAkadPembiayaan",
    "error_code" : "EF010",
    "validation" : "length must be 3 characters",
  },
  {
    "cid" : 109,
    "segment_name" : "F01",
    "v_column" : "kodeAkadKreditatauAkadPembiayaan",
    "error_code" : "EF011",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 110,
    "segment_name" : "F01",
    "v_column" : "nomorAkadAwal",
    "error_code" : "EF012",
    "validation" : "column is mandatory",
    "description" : "if kategori kredit atau pembiayaan dengan perjanjian",
  },
  {
    "cid" : 111,
    "segment_name" : "F01",
    "v_column" : "TanggalAkadAwal",
    "error_code" : "EF013",
    "validation" : "length must be 8 characters",
    "description" : "yyyymmdd = 19880425",
  },
  {
    "cid" : 112,
    "segment_name" : "F01",
    "v_column" : "TanggalAkadAwal",
    "error_code" : "EF014",
    "validation" : "column is mandatory",
    "description" : "if kategori kredit atau pembiayaan dengan perjanjian",
  },
  {
    "cid" : 113,
    "segment_name" : "F01",
    "v_column" : "nomorAkadAkhir",
    "error_code" : "EF015",
    "validation" : "column is mandatory",
    "description" : "if kategori kredit atau pembiayaan dengan perjanjian",
  },
  {
    "cid" : 114,
    "segment_name" : "F01",
    "v_column" : "tanggalAkadAkhir",
    "error_code" : "EF016",
    "validation" : "length must be 8 characters",
    "description" : "yyyymmdd = 19880425",
  },
  {
    "cid" : 115,
    "segment_name" : "F01",
    "v_column" : "tanggalAkadAkhir",
    "error_code" : "EF017",
    "validation" : "column is mandatory",
    "description" : "if kategori kredit atau pembiayaan dengan perjanjian",
  },
  {
    "cid" : 116,
    "segment_name" : "F01",
    "v_column" : "frekuensiPerpanjanganFasilitasKreditatauPembiayaan",
    "error_code" : "EF018",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 117,
    "segment_name" : "F01",
    "v_column" : "tanggalAwalKreditatauPembiayaan",
    "error_code" : "EF019",
    "validation" : "length must be 8 characters",
    "description" : "yyyymmdd = 19880425",
  },
  {
    "cid" : 118,
    "segment_name" : "F01",
    "v_column" : "tanggalAwalKreditatauPembiayaan",
    "error_code" : "EF020",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 119,
    "segment_name" : "F01",
    "v_column" : "tanggalMulai",
    "error_code" : "EF021",
    "validation" : "length must be 8 characters",
    "description" : "yyyymmdd = 19880425",
  },
  {
    "cid" : 120,
    "segment_name" : "F01",
    "v_column" : "tanggalMulai",
    "error_code" : "EF022",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 121,
    "segment_name" : "F01",
    "v_column" : "tanggalJatuhTempo",
    "error_code" : "EF023",
    "validation" : "length must be 8 characters",
    "description" : "yyyymmdd = 19880425",
  },
  {
    "cid" : 122,
    "segment_name" : "F01",
    "v_column" : "tanggalJatuhTempo",
    "error_code" : "EF024",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 123,
    "segment_name" : "F01",
    "v_column" : "kodeKategoriDebitur",
    "error_code" : "EF025",
    "validation" : "length must be 2 characters",
  },
  {
    "cid" : 124,
    "segment_name" : "F01",
    "v_column" : "kodeKategoriDebitur",
    "error_code" : "EF026",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 125,
    "segment_name" : "F01",
    "v_column" : "kodeJenisPenggunaan",
    "error_code" : "EF027",
    "validation" : "length must be 1 characters",
  },
  {
    "cid" : 126,
    "segment_name" : "F01",
    "v_column" : "kodeJenisPenggunaan",
    "error_code" : "EF028",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 127,
    "segment_name" : "F01",
    "v_column" : "kodeOrientasiPenggunaan",
    "error_code" : "EF029",
    "validation" : "length must be 1 characters",
  },
  {
    "cid" : 128,
    "segment_name" : "F01",
    "v_column" : "kodeOrientasiPenggunaan",
    "error_code" : "EF030",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 129,
    "segment_name" : "F01",
    "v_column" : "kodeSektorEkonomi",
    "error_code" : "EF031",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 130,
    "segment_name" : "F01",
    "v_column" : "kodeSektorEkonomi",
    "error_code" : "EF032",
    "validation" : "length must be 6 characters",
  },
  {
    "cid" : 131,
    "segment_name" : "F01",
    "v_column" : "kodeKabupatenatauKota_Lokasi_Proyek",
    "error_code" : "EF033",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 132,
    "segment_name" : "F01",
    "v_column" : "kodeKabupatenatauKota_Lokasi_Proyek",
    "error_code" : "EF034",
    "validation" : "Kode Kabupaten atau Kota is not active",
  },
  {
    "cid" : 133,
    "segment_name" : "F01",
    "v_column" : "nilaiProyek",
    "error_code" : "EF035",
    "validation" : "column is mandatory",
    "description" : "if jenis penggunaan adalah kredit atau pembiayaan modal kerja atau kredit \r\natau pembiayaan investasi",
  },
  {
    "cid" : 134,
    "segment_name" : "F01",
    "v_column" : "kodeValuta",
    "error_code" : "EF036",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 135,
    "segment_name" : "F01",
    "v_column" : "sukuBungaatauImbalan",
    "error_code" : "EF037",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 136,
    "segment_name" : "F01",
    "v_column" : "jenisSukuBungaatauImbalan",
    "error_code" : "EF038",
    "validation" : "length must be 1 characters",
  },
  {
    "cid" : 137,
    "segment_name" : "F01",
    "v_column" : "jenisSukuBungaatauImbalan",
    "error_code" : "EF039",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 138,
    "segment_name" : "F01",
    "v_column" : "kreditatauPembiayaanProgramPemerintah",
    "error_code" : "EF040",
    "validation" : "length must be 2 characters",
  },
  {
    "cid" : 139,
    "segment_name" : "F01",
    "v_column" : "kreditatauPembiayaanProgramPemerintah",
    "error_code" : "EF041",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 140,
    "segment_name" : "F01",
    "v_column" : "asalKreditatauPembiayaanTakeover",
    "error_code" : "EF042",
    "validation" : "column is mandatory",
    "description" : "if fasilitas kredit atau pembiayaan merupakan fasilitas takeover dari Pelapor lain",
  },
  {
    "cid" : 141,
    "segment_name" : "F01",
    "v_column" : "sumberDana",
    "error_code" : "EF043",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 142,
    "segment_name" : "F01",
    "v_column" : "plafonAwal",
    "error_code" : "EF044",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 143,
    "segment_name" : "F01",
    "v_column" : "plafon",
    "error_code" : "EF045",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 144,
    "segment_name" : "F01",
    "v_column" : "realisasiatauPencairanBulanBerjalan",
    "error_code" : "EF046",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 145,
    "segment_name" : "F01",
    "v_column" : "denda",
    "error_code" : "EF047",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 146,
    "segment_name" : "F01",
    "v_column" : "bakiDebet",
    "error_code" : "EF048",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 147,
    "segment_name" : "F01",
    "v_column" : "nilaiDalamMataUangAsal",
    "error_code" : "EF049",
    "validation" : "column is mandatory",
    "description" : "if kredit atau pembiayaan dengan mata uang selain Rupiah",
  },
  {
    "cid" : 148,
    "segment_name" : "F01",
    "v_column" : "kodeKualitasKreditatauPembiayaan",
    "error_code" : "EF050",
    "validation" : "length must be 1 characters",
  },
  {
    "cid" : 149,
    "segment_name" : "F01",
    "v_column" : "kodeKualitasKreditatauPembiayaan",
    "error_code" : "EF051",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 150,
    "segment_name" : "F01",
    "v_column" : "tanggalMacet",
    "error_code" : "EF052",
    "validation" : "column is mandatory",
    "description" : "if fasilitas kredit atau pembiayaan yang dilaporkan dinyatakan macet",
  },
  {
    "cid" : 151,
    "segment_name" : "F01",
    "v_column" : "tanggalMacet",
    "error_code" : "EF053",
    "validation" : "length must be 8 characters",
    "description" : "yyyymmdd = 19880425",
  },
  {
    "cid" : 152,
    "segment_name" : "F01",
    "v_column" : "kodeSebabMacet",
    "error_code" : "EF054",
    "validation" : "length must be 2 characters",
  },
  {
    "cid" : 153,
    "segment_name" : "F01",
    "v_column" : "kodeSebabMacet",
    "error_code" : "EF055",
    "validation" : "column is mandatory",
    "description" : "if fasilitas kredit atau pembiayaan yang dilaporkan dinyatakan macet",
  },
  {
    "cid" : 154,
    "segment_name" : "F01",
    "v_column" : "tunggakanPokok",
    "error_code" : "EF056",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 155,
    "segment_name" : "F01",
    "v_column" : "tunggakanBungaatauImbalan",
    "error_code" : "EF057",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 156,
    "segment_name" : "F01",
    "v_column" : "jumlahHariTunggakan",
    "error_code" : "EF058",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 157,
    "segment_name" : "F01",
    "v_column" : "frekuensiTunggakan",
    "error_code" : "EF059",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 158,
    "segment_name" : "F01",
    "v_column" : "frekuensiRestrukturirasi",
    "error_code" : "EF060",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 159,
    "segment_name" : "F01",
    "v_column" : "tanggalRestrukturisasiAwal",
    "error_code" : "EF061",
    "validation" : "column is mandatory",
    "description" : "if fasilitas kredit atau pembiayaan yang dilaporkan pernah direstrukturisasi",
  },
  {
    "cid" : 160,
    "segment_name" : "F01",
    "v_column" : "tanggalRestrukturisasiAwal",
    "error_code" : "EF062",
    "validation" : "length must be 8 characters",
    "description" : "yyyymmdd = 19880425",
  },
  {
    "cid" : 161,
    "segment_name" : "F01",
    "v_column" : "tanggalRestrukturisasiAkhir",
    "error_code" : "EF063",
    "validation" : "length must be 8 characters",
    "description" : "yyyymmdd = 19880425",
  },
  {
    "cid" : 162,
    "segment_name" : "F01",
    "v_column" : "tanggalRestrukturisasiAkhir",
    "error_code" : "EF064",
    "validation" : "column is mandatory",
    "description" : "if fasilitas kredit atau pembiayaan yang dilaporkan pernah direstrukturisasi",
  },
  {
    "cid" : 163,
    "segment_name" : "F01",
    "v_column" : "kodeCaraRestrukturisasi",
    "error_code" : "EF065",
    "validation" : "length must be 2 characters",
    "description" : "",
  },
  {
    "cid" : 164,
    "segment_name" : "F01",
    "v_column" : "kodeCaraRestrukturisasi",
    "error_code" : "EF066",
    "validation" : "column is mandatory",
    "description" : "if fasilitas kredit atau pembiayaan yang dilaporkan pernah direstrukturisasi",
  },
  {
    "cid" : 165,
    "segment_name" : "F01",
    "v_column" : "kodeKondisi",
    "error_code" : "EF067",
    "validation" : "length must be 2 characters",
  },
  {
    "cid" : 166,
    "segment_name" : "F01",
    "v_column" : "kodeKondisi",
    "error_code" : "EF068",
    "validation" : "column is mandatory",
  },
  {
    "cid" : 167,
    "segment_name" : "F01",
    "v_column" : "tanggalKondisi",
    "error_code" : "EF069",
    "validation" : "length must be 8 characters",
    "description" : "yyyymmdd = 19880425",
  },
  {
    "cid" : 168,
    "segment_name" : "F01",
    "v_column" : "tanggalKondisi",
    "error_code" : "EF070",
    "validation" : "column is mandatory",
    "description" : "if kolom kode kondisi berisi selain “00”",
  },
  {
    "cid" : 169,
    "segment_name" : "F01",
    "v_column" : "kodeKantorCabang",
    "error_code" : "EF071",
    "validation" : "column is mandatory",
  }
];
